package com.example.currencyflow.classes

import com.example.currencyflow.R

enum class Currency(val symbol: String, val icon: Int) {
    USD("USD", R.drawable.us),
    EUR("EUR", R.drawable.eu),
    GBP("GBP", R.drawable.gb),
    JPY("JPY", R.drawable.jp),
    PLN("PLN", R.drawable.pl),
    /*
    AUD("AUD"),
    CAD("CAD"),
    CHF("CHF"),
    CNY("CNY"),
    SEK("SEK"),
    NZD("NZD"),
    NOK("NOK"),
    KRW("KRW"),
    MXN("MXN"),
    SGD("SGD"),
    HKD("HKD"),
    INR("INR"),
    RUB("RUB"),
    ZAR("ZAR"),
    BRL("BRL"),
    TRY("TRY"),
    THB("THB"),

    IDR("IDR"),
    MYR("MYR"),
    PHP("PHP"),
    TWD("TWD"),
    ARS("ARS"),
    CLP("CLP"),
    COP("COP"),
    CZK("CZK"),
    DKK("DKK"),
    HUF("HUF"),
    ILS("ILS"),
    KES("KES"),
    KWD("KWD"),
    MAD("MAD"),
    NAD("NAD"),
    NGN("NGN"),
    PEN("PEN"),
    PKR("PKR"),
    RON("RON"),
    SAR("SAR"),
    UGX("UGX"),
    UYU("UYU"),
    VND("VND"),
    XAF("XAF"),
    XOF("XOF"),
    XPF("XPF"),

     */
}